### PR TITLE
Improves code efficiency and reformat

### PR DESCRIPTION
**Pull request by Pythonic-Rainbow**

### CODE REVIEW

**Comment by sbhadr** [comment]
I'm assuming that this is either an error or a work in progress. Please clarify.

**Comment by Pythonic-Rainbow** [comment]
It's WOP, basically tidy up things and changed some code to run more efficiently

**Review by sbhadr — APPROVED** [review]
Looks good on my end. Has this been tested?

**Comment by Pythonic-Rainbow** [comment]
They are just reformats so yes

**Pull request merged**
