### PR TITLE
Subscriber leaderboard

### PR DESCRIPTION
**Pull request by iranathan**

### CODE REVIEW

**Comment by iranathan** [comment]
image tested

**Comment by sbhadr** [comment]
I'm questioning why this is needed.

**Comment by iranathan** [comment]
I think it would be good for users to see witch libs are the most popular.

**Comment by Pythonic-Rainbow** [comment]
Well, it doesn't hurt to add such a feature, but yeah not necessary  
Speaking of leaderboard, I am actually interested in what command do people use the most instead.

**Review by sbhadr — APPROVED** [review]
Works on my end. Merging.

**Pull request merged**
