### PR TITLE
Further async changes

### PR DESCRIPTION
**Pull request by Pythonic-Rainbow**
Tackles #24 

Work in progress

### CODE REVIEW

**Review by sbhadr — COMMENTED** [review]
Has this been tested extensively?

**Comment by Pythonic-Rainbow** [comment]
I haven't tested `?subscribe` and `?pingnews` yet. But other than thosee I am quite confident it will work. Doesn't really improve performance per command, but reduces blocking for the entire bot.

**Comment by sbhadr** [comment]
> I haven't tested `?subscribe` and `?pingnews` yet. But other than thosee I am quite confident it will work. Doesn't really improve performance per command, but reduces blocking for the entire bot.

Make sure all things are tested before it's pulled and put into review. All merges are automatically synced with the running instance and if there's an issue, it'll wreak havoc on the current system.

**Comment by Pythonic-Rainbow** [comment]
I can't test those because I don't have `xxx news` roles in my own guild

**Review by sbhadr — APPROVED** [review]
I've tested this against the dev build. Seems to work perfectly. Will not merge until https://github.com/RbxAPI/Docs-Bot/issues/25 is completed on my end.

**Comment by Pythonic-Rainbow** [comment]
Yep. Those trials without responses are due to bot missing permissions. Not a problem when merged.
image

**Comment by Pythonic-Rainbow** [comment]
Haven't done anything on `?doc ?docs ?leaderboard` yet, but tbh I think there's nothing to do atm, will think about it soon.  
I'll do #23 after these async changes. You might want to wait me finish it or just merge this PR.

**Review by sbhadr — APPROVED** [review]

**Comment by sbhadr** [comment]
I had to edit some things and decided to add some features to this branch. 

I'll go ahead and merge this.

**Pull request merged**
